### PR TITLE
Upstream 10

### PR DESCRIPTION
**Pull request by motobob**
get latest upstream so to be able to merge things back finally.

@alexturkin

### CODE REVIEW

**Comment by motobob** [comment]
closing to check travis

**Comment by alexturkin** [comment]
@motobob did you just `git merge upstream` to master branch? or there were some conflicts?

**Comment by alexturkin** [comment]
When I had to pull dynamo-db changes, I had to resolve lot of conflicts, so it wasn't easy.

**Comment by motobob** [comment]
@alexturkin yes, i did `git merge gleber/master` and resolved all the conflicts manually wit extra caution :)

**Pull request merged**
