### PR TITLE
Empty map fix

### PR DESCRIPTION
**Pull request by vipinsingh211**
As discussed at [fix #322](https://github.com/erlcloud/erlcloud/pull/322)

### CODE REVIEW

**Comment by nalundgaard** [comment]
I believe that it would be better to simply merge upstream changes from erlcloud/erlcloud into alertlogic/erlcloud. You shouldn't just copy-paste changes from one repo to another with different commits, it can make it that much harder to merge things back together.

Plus, if we are pulling changes into alertlogic, I need alertlogic/erlcloud#320 as well. ;)

**Comment by nalundgaard** [comment]
I'm going to close this. Let us know the timeframe that you need this. I will work with @motobob to get upstream erlcloud/erlcloud merged down to alertlogic/erlcloud.

**Comment by pointtonull** [comment]
Hi!

We created a workaround dirty implementing this patch in our fork. So, we need this feature, but we are fixed by now.

Cheers 🍺

**Comment by nalundgaard** [comment]
Sounds good. This should be addressed when #131 is merged, assuming @motobob is good with it.

**Comment by motobob** [comment]
@pointtonull @vipinsingh211 you now can remove as i just merged it all

> workaround dirty implementing this patch

**Pull request closed without merging**
